DROP SEQUENCE brd_group_seq;
DROP SEQUENCE brd_cate_seq;
DROP SEQUENCE brd_seq;
DROP SEQUENCE img_file_seq;
DROP SEQUENCE brd_cmt_seq;

CREATE SEQUENCE brd_group_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE brd_cate_seq
START WITH 1ㄴ
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE brd_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE img_file_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE brd_cmt_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1;